---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"

- name: add kibana user to elasticsearch group
  user:
    name: kibana
    groups: elasticsearch
    append: yes

- name: configure log folder
  file:
    path: "{{ kibana_logging_dest | dirname }}"
    state: directory
    owner: kibana
  when: kibana_logging_dest != "stdout"

- name: configure log rotate
  copy:
    dest: /etc/logrotate.d/kibana
    owner: root
    content: |
      "{{ kibana_logging_dest | basename }}" {
        missingok
        notifempty
        sharedscripts
        postrotate
        /bin/kill -HUP $(cat /var/run/kibana.pid 2>/dev/null) 2>/dev/null
        endscript
      }
  when: kibana_logging_dest != "stdout"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

